-- TODO: answer here
ALTER TABLE users
ADD COLUMN phone VARCHAR(50) NULL,
ADD COLUMN address VARCHAR(255) NULL,
ADD COLUMN department VARCHAR(255) NULL,
ADD COLUMN division VARCHAR(255) NULL,
ADD COLUMN position VARCHAR(255) NULL;